#!/bin/bash

. ./scripts/version

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

case "$(uname -m)" in
  "x86_64")
    add-apt-repository  "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    ;;
  "aarch64")
    add-apt-repository  "deb [arch=arm64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    ;;
  *)
    echo "Unsupported architecture for building"
    exit 1
    ;;

apt-get -y update && apt-get install -y docker-ce-cli

git clone https://github.com/rancher/containerd-packaging.git

cd containerd-packaging

make REF=${RPM_VERSION} docker.io/library/centos:8